// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCounterChange();
void onScheduleTestChange();
void onLightChange();
void onSwitctChange();
void onTimeReadChange();

int counter;
CloudSchedule schedule_test;
bool light;
bool switct;
CloudTime time_read;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(counter, READWRITE, ON_CHANGE, onCounterChange);
  ArduinoCloud.addProperty(schedule_test, READWRITE, ON_CHANGE, onScheduleTestChange);
  ArduinoCloud.addProperty(light, READWRITE, ON_CHANGE, onLightChange);
  ArduinoCloud.addProperty(switct, READWRITE, ON_CHANGE, onSwitctChange);
  ArduinoCloud.addProperty(time_read, READWRITE, ON_CHANGE, onTimeReadChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
